# Basics of Data Frame

In [1]:
# Exp: 3

In [ ]:
# Aim : Basics of Data Frame

In [3]:
# Name: Rushikesh Nilkhan
# Roll no: 43
# Section: B
# Subject: ET1

In [5]:
# Basics of Data Frame

# Creating a Series

In [6]:
# Importing the pandas library
import pandas as pd

In [11]:
Friends=["Om", "Shahid", "Ansh", "Rushi", "Jay"]

In [12]:
Friends

['Om', 'Shahid', 'Ansh', 'Rushi', 'Jay']

In [13]:
rollList = pd.Series(Friends, index=[20,57,40,43,26])

In [14]:
rollList

20        Om
57    Shahid
40      Ansh
43     Rushi
26       Jay
dtype: object

# Creating a Data Frame

In [46]:
df = pd.DataFrame([[27, 15, 10, 5],[2, 10, 18, 22],[15, 26, 0, 20],[7, 11, 13, 20]],
                        columns = ["CD","DSS","DBMS","CAO"]
                        )

In [47]:
df

   CD  DSS  DBMS  CAO
0  27   15    10    5
1   2   10    18   22
2  15   26     0   20
3   7   11    13   20

In [48]:
df.shape

(4, 4)

In [49]:
df.size

16

In [50]:
df.ndim

2

In [51]:
df2 = pd.DataFrame([[27, 10, 11, 0]],
                        columns = ["CD","DSS","DBMS","CAO"]
                        )

In [52]:
df3 = pd.concat([df, df2], ignore_index=True)

In [53]:
df3

   CD  DSS  DBMS  CAO
0  27   15    10    5
1   2   10    18   22
2  15   26     0   20
3   7   11    13   20
4  27   10    11    0

# Adding Record (Columns) to Data Frame

In [56]:
df3["DM"]=[12, 18, 2, 8, 11]

In [57]:
df3

   CD  DSS  DBMS  CAO  DM
0  27   15    10    5  12
1   2   10    18   22  18
2  15   26     0   20   2
3   7   11    13   20   8
4  27   10    11    0  11

# Deleting Record (Row) From Data Frame

In [58]:
df4= df3.drop(index=[1])

In [59]:
df4

   CD  DSS  DBMS  CAO  DM
0  27   15    10    5  12
2  15   26     0   20   2
3   7   11    13   20   8
4  27   10    11    0  11

In [61]:
print("Mean of DSS:", df4["DSS"].mean())

Mean of DSS: 15.5

In [62]:
print("Mean of DSS:", df4["DSS"].median())

Mean of DSS: 13.0

In [63]:
print("Mean of DSS:", df4["DSS"].mode())

Mean of DSS: 0    10
1    11
2    15
3    26
Name: DSS, dtype: int64