# Simple Linear Regression

In [ ]:
# exp 7

In [ ]:
# Name: Rushikesh Nilkhan
# Roll no: 43
# Section: B
# Subject: ET1

In [14]:
# importing the pandas library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
import os

In [16]:
os.getcwd()

'C:\\Users\\rushi\\OneDrive\\Desktop'

In [17]:
os.chdir("C:\\Users\\rushi\\OneDrive\\Desktop")

In [18]:
data=pd.read_csv("Salary_Data.csv")

In [19]:
data.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [20]:
data.tail()

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [21]:
data.shape

(30, 2)

In [22]:
data.size

60

In [23]:
data.ndim

2

In [24]:
data.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [26]:
data.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [46]:
data.isnull()

    YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False

In [47]:
data.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [29]:
data.isna().any()

YearsExperience    False
Salary             False
dtype: bool

In [49]:
#Assiging values in X & Y
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [50]:
print(X)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]

In [51]:
print(y)

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]

In [30]:
x=data.drop('Salary',axis=1)

In [31]:
x.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [32]:
y=data.Salary

In [33]:
y.head()

0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
Name: Salary, dtype: float64

In [52]:
#Splitting testdata into X_train,X_test,y_train,y_test
from sklearn.model_selection import train_test_split

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.30)

In [36]:
x_train.shape

(21, 1)

In [37]:
x_test.shape

(9, 1)

In [54]:
print(x_train)

    YearsExperience
22              7.9
5               2.9
16              5.1
8               3.2
14              4.5
23              8.2
20              6.8
1               1.3
29             10.5
6               3.0
4               2.2
18              5.9
19              6.0
9               3.7
7               3.2
25              9.0
3               2.0
0               1.1
21              7.1
15              4.9
12              4.0

In [56]:
print(x_test)

    YearsExperience
2               1.5
28             10.3
13              4.1
10              3.9
26              9.5
24              8.7
27              9.6
11              4.0
17              5.3

In [57]:
print(y_train)

22    101302.0
5      56642.0
16     66029.0
8      64445.0
14     61111.0
23    113812.0
20     91738.0
1      46205.0
29    121872.0
6      60150.0
4      39891.0
18     81363.0
19     93940.0
9      57189.0
7      54445.0
25    105582.0
3      43525.0
0      39343.0
21     98273.0
15     67938.0
12     56957.0
Name: Salary, dtype: float64

# Model Fitting

In [38]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [39]:
#Assigning coeffficent (slope) to m
m = LR.coef_

In [40]:
print("Coefficient :", m)

Coefficient : [9360.26128619]

In [41]:
#Assigning Y-intercept to a
c = LR.intercept_

In [42]:
print("Intercept :", c)

Intercept : 26777.39134119764

In [43]:
Accuracy = LR.score(x_test, y_test)
Accuracy

0.9740993407213511

# Evaluation metrices

In [44]:
from sklearn import metrics

In [45]:
Accuracy = LR.score(x_test, y_test)
Accuracy

0.9740993407213511